# Generated by Django 3.2.6 on 2021-08-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
